name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build parser
        run: yarn workspace xd-crossword-tools-parser build

      - name: Build lib
        run: yarn workspace xd-crossword-tools build

      - name: Type check
        run: yarn type-check

      - name: Run tests
        run: yarn test --run

  website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build parser
        run: yarn workspace xd-crossword-tools-parser build

      - name: Build lib
        run: yarn workspace xd-crossword-tools build

      - name: Build website
        run: |
          cd website
          yarn build
